### ISSUE TITLE
100 th ISSUE LETS GOOOO

### ISSUE THREAD

**Issue by NotDevilhunter** [Kopamed/Raven-bPLUS#100]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Version of Raven [e.g. 1.0.16 beta 44 main] 

**Additional context**

**Comment by BerBerOnGithub** [comment]
I know it's the 100th, but you don't need to make 3 tickets at the same time.

**Comment by PndaBoi** [comment]
Fr
