### ISSUE TITLE
Add Killaura.

### ISSUE THREAD

**Issue by AlexBartles2012** [Kopamed/Raven-bPLUS#105]
**Is your feature request related to a problem? Please describe.**
Nope, it isn't.

**Describe the solution you'd like**
I want you guys to add killaura to the client. A recommendation I have to base it on is Vape V4.

**Describe alternatives you've considered**
No alternatives I've considered.

**Additional context**

**Comment by medicinalcocaine3434** [comment]
ratio + duplicate issue + this is a ghost client not a hybrid client

**Comment by Cweepaw** [comment]
ratio + duplicate issue + this is a ghost client not a hybrid client

**Comment by Nukemo** [comment]
yeah dude ghost client totally has vanilla bhop and glide and vanilla fly and also slyport also lets not forget vanilla speed and autoblock this is ghost client defo not hybrid

**Comment by Cweepaw** [comment]
cum

**Comment by master7720** [comment]
> cu

> yeah dude ghost client totally has vanilla bhop and glide and vanilla fly and also slyport also lets not forget vanilla speed and autoblock this is a ghost client defo not hybrid

you left @Cweepaw speechless

**Comment by Cweepaw** [comment]
> you left @Cweepaw speechless

nah i just have to write 5 school essays that's not much right I totally have time to respond haha yep

**Comment by jseuff** [comment]
Killaura is in the [to-do](https://github.com/Kopamed/Raven-bPLUS/projects/1) page under 1.0.17. Make sure to look at the to-do page before suggesting

**Comment by AlexBartles2012** [comment]
> Killaura is in the [to-do](https://github.com/Kopamed/Raven-bPLUS/projects/1) page under 1.0.17. Make sure to look at the to-do page before suggesting

ok

**Comment by AlexBartles2012** [comment]
im waiting for the killaura release lol

**Comment by master7720** [comment]
> > you left @Cweepaw speechless
> 
> nah i just have to write 5 school essays that's not much right I totally have time to respond haha yep
> 
> I am definitely not making excuses

full on cap
