### ISSUE TITLE
unshift delay for safe walk

### ISSUE THREAD

**Issue by 0xff01WasTaken** [Kopamed/Raven-bPLUS#11]
to make it less detectable and look more legit

**Comment by Cypphi** [comment]
Make the delay option use ingame ticks rather than ms, I would like to be able to 1 tick speedbridge so it looks like im god bridging :trollface:

**Comment by Kopamed** [comment]
Already added. @Cypphi making the delays in ticks would make it very hard to customize and it still would not look like you are 1 tick shift bridging because of how I determine if you are on the edge of a block
