### ISSUE TITLE
Whenever I go to the toilet it crashes the game

### ISSUE THREAD

**Issue by Cweepaw** [Kopamed/Raven-bPLUS#110]
**Describe the bug**
When I go to the toilet, the game crashes. When I don't, it doesn't crash.

**To Reproduce**

**Expected behavior**
Minecraft doesn't crash.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows XP
 - Browser [e.g. chrome, safari] Opera GX
 - Version of Raven [e.g. 1.0.16 beta 44 main] Experimental

**Additional context**

**Comment by qazwsx-11** [comment]
pov https://www.youtube.com/watch?v=rKC38du7h8k

**Comment by DaberPani** [comment]
LMFAO

**Comment by PndaBoi** [comment]
Haha

**Comment by JMRaichDev** [comment]
lmao
