### ISSUE TITLE
Discord deleted / termed?

### ISSUE THREAD

**Issue by SamIsOnMC** [Kopamed/Raven-bPLUS#112]
Im suddenly not in the discord anymore. Someone else has the same. Did the dc get termed / deleted or some shit?

**Comment by JMRaichDev** [comment]
I don't know if it has been termed.
Here are the 2 main links:
 - **Kopamed's Mods**: https://discord.com/invite/XhVt9NMtBE
 - **Raven Client**: https://discord.com/invite/QQMQfCRyNP
