### ISSUE TITLE
[Bug] Crashes On ARM

### ISSUE THREAD

**Issue by timof121** [Kopamed/Raven-bPLUS#16]
Hello kopamed, could you please add a error handler if discordrpc doesn't load? I know every client dev hates ARM but please, i dont think its so hard

My problem is that when i play with b plus and press rshift, theg ame crashes becaseu there no discordrpc lib on arm 
https://hastebin.com/gejebexeku.properties

I use debian ARM (Linux)
Thanks!

**Comment by JMRaichDev** [comment]
Thank you for taking time to report the issue.
It will be fixed soon

**Comment by timof121** [comment]
Thanks. Just test, kopamed already fixed it in https://github.com/Kopamed/Raven-bPLUS/commit/74ab5f07e1dacb8e76bcf0131e322affbec5494b !
