### ISSUE TITLE
[suggestion] add autoupdate

### ISSUE THREAD

**Issue by erxson** [Kopamed/Raven-bPLUS#22]
just make autoupdate

**Comment by erxson** [comment]
I saw it in atomic, so can you do it?

**Comment by NightTabGit** [comment]
Kopamed didn't want to do it as it gives him the option to add nalware or RAT the program, which he doesn't want to do. It would be nice though.

**Comment by erxson** [comment]
but everyone can see github link

**Comment by erxson** [comment]
but you im agree with you

**Comment by erxson** [comment]
:(

**Comment by Kopamed** [comment]
Very bad idea. As most of the releases are beta branches, there will no doubt be very unstable builds. I don´t want everyone using those as obviously, it will greatly decrease the quality of the client.

**Comment by erxson** [comment]
you can make "stable/beta" option
