### ISSUE TITLE
Problem with little text 

### ISSUE THREAD

**Issue by yarik3032** [Kopamed/Raven-bPLUS#37]
![image](https://user-images.githubusercontent.com/91082264/134037774-f58feef2-e0da-4045-8fc5-254f2f8a7950.png)

i forgor how to fix it i tried to use english and unicode nothing

**Comment by timof121** [comment]
I think its patcher

**Comment by BobIsMyManager** [comment]
I dont get this issue with patcher

**Comment by dezintgarecja** [comment]
i do get this issue without patcher
