### ISSUE TITLE
autotool and blockhit failing to work

### ISSUE THREAD

**Issue by dezintgarecja** [Kopamed/Raven-bPLUS#39]
TLDR: autotool work, cant shear wool and then not work

So I was just disbanding a party on Hypixel and out of nowhere the client nuked itself. I don't think _this_ is an issue - I'm a dumbass after all.
So I reinstalled the client, updating it by the way, and enabled all of my usual modules. I played a test game, autotool works, and then it fails to shear wool and just completely ceases to work. It's probably something i messed up, but I still would like to know what I messed up.

**Comment by dezintgarecja** [comment]
Also blockhit seems to not work at all, to clarify I downloaded the latest version [oct 12th]

**Comment by Vexusz** [comment]
try disable and enable it
