### ISSUE TITLE
[SUGGESTION] Make exe installer

### ISSUE THREAD

**Issue by A216DISCORD** [Kopamed/Raven-bPLUS#65]
Please make exe installer for Raven b+ like this:
https://onedrive.live.com/download?cid=8CAE3AB2682F129C&resid=8CAE3AB2682F129C%212045&authkey=ANeWes8hYsQ9mVw

**Comment by RaidLocked** [comment]
?
retard alert. its a forge mod. if you dont know how to install a forge mod. you shouldnt be hacking

**Comment by Kopamed** [comment]
No. This is pointless as this is a forge mod. All you have to do is to drag it to your mods folder. It does not get more complicated than that. However, if I ever do make b+ injectable, I will make sure that it has an installer.
