### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by AadiCJ** [Kopamed/Raven-bPLUS#66]
I downloaded a beta version of it, and now can't get a stable version lol

**Comment by A216DISCORD** [comment]
https://onedrive.live.com/download?cid=8CAE3AB2682F129C&resid=8CAE3AB2682F129C%212047&authkey=AGxzpT7PvUTlFf0
You can try it to install the stable version
VirusTotal:https://www.virustotal.com/gui/file-analysis/N2MzMWM5NTc0MGY2YjFkYzg1MjM4YmRkNGUyY2U0OGE6MTYzODQzOTkxNg==

**Comment by dudethis** [comment]
ummmmmmm no don't download exes from random people on the internet.

**Comment by master7720** [comment]
> https://onedrive.live.com/download?cid=8CAE3AB2682F129C&resid=8CAE3AB2682F129C%212047&authkey=AGxzpT7PvUTlFf0 You can try it to install the stable version VirusTotal:https://www.virustotal.com/gui/file-analysis/N2MzMWM5NTc0MGY2YjFkYzg1MjM4YmRkNGUyY2U0OGE6MTYzODQzOTkxNg==

your not even a dev

**Comment by AadiCJ** [comment]
I think I will wait for a dev to reply, but theres no point, schools starting soon.

**Comment by dudethis** [comment]
omfg just join the discord
they have a fairly new version in #downloads
(they understand the website is down)

**Comment by dickinyourmouth** [comment]
> omfg just join the discord they have a fairly new version in #downloads (they understand the website is down)

Can you give me their discord ?

**Comment by AadiCJ** [comment]
> omfg just join the discord they have a fairly new version in #downloads (they understand the website is down)

Ok thanks :D

**Comment by AadiCJ** [comment]
> omfg just join the discord they have a fairly new version in #downloads (they understand the website is down)

OK Thanks :D
