### ISSUE TITLE
[suggestion]Lag-Remover

### ISSUE THREAD

**Issue by RyanTNTKing** [Kopamed/Raven-bPLUS#71]
add lag remover(not fps spoofer, its litterly improve fps)
to fix too many models lead minecraft lag(what i think? why don't i just stop hacking?)
or...update new ways to imrprove the whole performance of the raven b+ in new version.

**Comment by Kopamed** [comment]
How about installing optifine. Raven B+ performance is being greatly improved in the new-base branch, which will soon be merged into main.
