### ISSUE TITLE
[suggestion] please make an already compiled java file 

### ISSUE THREAD

**Issue by wipsk** [Kopamed/Raven-bPLUS#72]
doing the whole gradel thing never works for me also the website dosent work

**Comment by ULTRAPranvv** [comment]
@wipsk Here is the download for it https://github.com/Kopamed/Raven-bPLUS/files/7698160/Raven.b%2B.zip

**Comment by drkhn1234** [comment]
> doing the whole gradel thing never works for me also the website dosent work

Hiya, I might have known what cause the problem with gradle build system. The project is bundled with a gradle wrapper (which is to make it portable so you do not have to install all of the gradle dependencies that are required for other stuff like developing, etc.) which is also called by the name "./gradlew" ('w' at the end stands for the wrapper), but is an old version that is 4.4 from 2015 which doesn't support any java 11 and newer hence why you may have build issues while you run the wrapper script. You might want to go installing java version that is older than JAVA 11, something like Java 8 should be fine, and try running the script for build.

**Comment by KadirFFM** [comment]
If you use an IDEA you can try to build the Gradle project via your IDEA.

**Comment by 182exe** [comment]
Have you tried looking harder into the git repository?

**Comment by Nukemo** [comment]
https://github.com/Kopamed/Raven-bPLUS/tree/main/build/libs

**Comment by Nukemo** [comment]
🤡

**Comment by 9qz** [comment]
ur fucking retarded

**Comment by wipsk** [comment]
yeah i was blind

**Comment by 182exe** [comment]
> yeah i was blind

Ur fine, we all make mistakes :)
