### ISSUE TITLE
Issues / suggestion about Raven B+ "Latest Experimental"

### ISSUE THREAD

**Issue by manhmct301** [Kopamed/Raven-bPLUS#76]
So I was using Raven B+ "Lastest Stable" and everything's fine until I try out the other version ( experimental ):
- Autoclick settings got messed from 15-20 to 13-16 ( I wonder this is a bug or feature since it might lose old autoclicker settings and decided to use the default value
- I always have 3.3-3.9 reach value & when I tested with a villager on local world and even players on multiplayer servers, I ended up reaching 4.89 blocks. Checked again and still the same settings ( 3.9 blocks ).
- ClientNameSpoofer doesn't change anything, even after a restart / reload config / retype in console. ( NameHider - or whatever I forgot, still works )

( everything above might be problems when I change version from Lastest Stable to Experimental, so if you do recognize them, just skip it :D )

Suggestions: Add ExplicitB9 Nametag to Stable ver. I had a hard time finding players since ESP/Chams/Tracers can't render them and only switched to Experimental for it but turns out there are bugs and even chance of turning on something I don't want ( speed 20CPS+ autoclicker bhop.... )

**Comment by PndaBoi** [comment]
I had the same issues with the auto clicker and my keystrokesmod was telling I was hitting 20+ cps whereas my other forge mod says 1 cps

**Comment by PndaBoi** [comment]
restarting would sometimes solve the issue

**Comment by Kopamed** [comment]
> Autoclick settings got messed from 15-20 to 13-16 ( I wonder this is a bug or feature since it might lose old autoclicker settings and decided to use the default value

Yeah, the experimental auto clicker code is a bit different and is probably quite buggy. I suggest you use stable if you can't pls
ay with this.

> I always have 3.3-3.9 reach value & when I tested with a villager on local world and even players on multiplayer servers, I ended up reaching 4.89 blocks. Checked again and still the same settings ( 3.9 blocks ).

Not much I can do about this. Ping and server lag is the cause of that. I will be adding a option in the new-base branch to try to stop hits which exceed the limit by predicting where the target will be when they actually get hit.

> ClientNameSpoofer doesn't change anything, even after a restart / reload config / retype in console. ( NameHider - or whatever I forgot, still works )

The only thing that client spoofer does is change the client name in the f3 screen. Does it work?

 > Suggestions: Add ExplicitB9 Nametag to Stable ver. I had a hard time finding players since ESP/Chams/Tracers can't render them and only switched to Experimental for it but turns out there are bugs and even chance of turning on something I don't want ( speed 20CPS+ autoclicker bhop.... )

Will do. I will also try to fix the b3 nametags while I am at it.

**Comment by manhmct301** [comment]
> The only thing that client spoofer does is change the client name in the f3 screen. Does it work?

Oh, I'm sorry, thought it will change everything like player's nametag in F5. Today I checked again and, it worked in F3.

Thanks for replying! Can someone close this? ( seems like I can't :0 )
