### ISSUE TITLE
Bugs in config system ( Raven B+ Stable )

### ISSUE THREAD

**Issue by manhmct301** [Kopamed/Raven-bPLUS#77]
Basically if I switch to a new config, using command line of course, some modules aren't disabled, such as Velocity,... Settings for some like Autoclicker is still the other's config setting, which is, they aren't bugged. But, the first time I experienced that bug, there are more which is also not disabled automatically like FastPlace, AutoPlace, Sprint,....

1. Load an existing config which has those bugged modules, or just turn on those
2. Load the other config which doesn't have those modules enabled 
3. Boom. I tested 8 times today ( 8 restarts ), and they're still bugged so I assume that's an actual bug

- I thought it was a bug in my config, but then I made another and still the same problem. However, you can try if deleting those old bugged configs works

About Minecraft / Client version:
- Stable Raven B+. I don't know if there is any newer version released yet, because when I head to Github, I see nothing
+ The Raven B+ release I'm using right now, downloaded it from 10 days ago
- I use with some mods like BetterFPS, Patcher 1.7.0, IGAccountSwitcher, but don't think it caused the bug

If you need a video about the bug as you don't really understand what I describe, reply and I would be really glad to help!

**Comment by Kopamed** [comment]
I am already aware of this issue and I am working on a better system on the new-base branch, which will soon be merged into stable.
