### ISSUE TITLE
Unable to launch the stable B+

### ISSUE THREAD

**Issue by SuchSunset** [Kopamed/Raven-bPLUS#85]
I somehow, I am unable to launch the game, and it says "keystrokesmod.module.ModuleSettingSlider cannot be cast to keystrokesmod.module.ModuleSettingDoubleSlider
Exit Code: -1"

Don't know how to reproduce

NOTE: I can launch with the lunar keystrokes but I keep getting the stackoverflow problem.

**Comment by 182exe** [comment]
Delete configs :)

**Comment by SuchSunset** [comment]
The configs in configs folder or configs not in the configs folder?

**Comment by SuchSunset** [comment]
But also; thanks for the help

**Comment by SuchSunset** [comment]
But it worked, thanks alot for the help man
