### ISSUE TITLE
Ability to set the gui scale

### ISSUE THREAD

**Issue by apoorvgupt479** [Kopamed/Raven-bPLUS#91]
**Is your feature request related to a problem? Please describe.**
I'm talking about the overall GUI encountered when pressing R-SHIFT. Some menus like the "combat" are too large to fit on the screen on some resolutions of the game.

**Describe the solution you'd like**
Please add a "scale" slider option in the GUI module in the "client" menu *or something*.

**Additional context**
Screenshot attached here
![raven](https://user-images.githubusercontent.com/64680081/152169342-832ed4cd-fbd1-4aad-97a2-a53980e0725b.png)
* I cannot configure auto-block in combat 
* I cannot configure player-esp in render 
* These are just a few examples

**Comment by Nukemo** [comment]
how small is your monitor bro 💀 
also there is auto gui rescaling in beta
you can change your gui scale through options>video settings to adjust gui scale in stable and experimental

**Comment by Nukemo** [comment]
how small is your monitor bro 💀 
also there is auto gui rescaling in beta
you can change your gui scale through options>video settings to adjust gui scale in stable and experimental

**Comment by Neooonmaxy** [comment]
Join discord https://discord.gg/v9Z8dS4taW

**Comment by Neooonmaxy** [comment]
@everyone  Join The Best Discord https://discord.gg/v9Z8dS4taW

**Comment by apoorvgupt479** [comment]
> how small is your monitor bro skull also there is auto gui rescaling in beta you can change your gui scale through options>video settings to adjust gui scale in stable and experimental also play in fullscreen

in full screen the gui rescales itself and becomes bigger so that does not solve the problem

**Comment by Neooonmaxy** [comment]
@everyone  Join The Best Discord https://discord.gg/v9Z8dS4taW

**Comment by abashir7866** [comment]
@Neooonmaxy kys piece of shit

**Comment by abashir7866** [comment]
Go advertise somewhere else
